export const ADD_MARKER = 'ADD_MARKER';
export const REMOVE_MARKER = 'REMOVE_MARKER';
export const UPDATE_MARKER = 'UPDATE_MARKER';

export const ADD_SEGMENT = 'ADD_SEGMENT';
export const REMOVE_SEGMENT = 'REMOVE_SEGMENT';
export const UPDATE_SEGMENT = 'UPDATE_SEGMENT';
